---
language: node_js
node_js:
  - "10"

branches:
  only:
    - master

sudo: required

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --no-lockfile --non-interactive --ignore-engines
  - bower install

script:
  - yarn lint:js
  - npm test
